// frontend/src/app/events/[slug]/page.tsx
import { notFound } from "next/navigation";
import { prisma } from "@/lib/prisma";
import {
  statusConfig,
  typeConfig,
  formatDateRange,
} from "@/lib/event";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { DivisionList } from "@/components/event/division-list";
import { ScheduleTimeline } from "@/components/event/schedule-timeline";
import { MedalTable, type ContingentStanding } from "@/components/event/medal-table";
import { BracketExplorer } from "@/components/event/bracket-explorer";
import {
  Calendar,
  MapPin,
  Phone,
  Mail,
  Users,
  Trophy,
  Clock,
  Target,
} from "lucide-react";

// hitung klasemen kontingen dari medali yang sudah ada
async function getStandings(eventId: string): Promise<ContingentStanding[]> {
  const medals = await prisma.medal.findMany({
    where: { eventId, contingentId: { not: null } },
    include: { contingent: true },
  });

  // kelompokkan per kontingen
  const map = new Map<string, ContingentStanding>();
  for (const m of medals) {
    if (!m.contingentId || !m.contingent) continue;
    const existing = map.get(m.contingentId);
    if (!existing) {
      map.set(m.contingentId, {
        contingent: { id: m.contingent.id, name: m.contingent.name, logoUrl: m.contingent.logoUrl },
        gold: 0,
        silver: 0,
        bronze: 0,
        total: 0,
        rank: 0,
      });
    }
    const entry = map.get(m.contingentId)!;
    if (m.type === "GOLD") entry.gold++;
    if (m.type === "SILVER") entry.silver++;
    if (m.type === "BRONZE") entry.bronze++;
    entry.total++;
  }

  // ranking: Gold > Silver > Bronze > Total
  const arr = Array.from(map.values()).sort(
    (a, b) =>
      b.gold - a.gold ||
      b.silver - a.silver ||
      b.bronze - a.bronze ||
      b.total - a.total
  );
  arr.forEach((s, i) => (s.rank = i + 1));
  return arr;
}

export default async function EventDetailPage({
  params,
}: {
  params: { slug: string };
}) {
  const event = await prisma.event.findUnique({
    where: { slug: params.slug, isPublic: true },
    include: {
      config: true,
      divisions: { orderBy: [{ discipline: "asc" }, { ageCategory: "asc" }] },
      schedule: { orderBy: { time: "asc" } },
      contingents: true,
    },
  });

  if (!event) notFound();

  const [standings, participantCount, matchCount] = await Promise.all([
    getStandings(event.id),
    prisma.participant.count({
      where: { division: { eventId: event.id }, status: "APPROVED" },
    }),
    prisma.match.count({ where: { division: { eventId: event.id } } }),
  ]);

  const status = statusConfig[event.status];
  const type = typeConfig[event.type];
  const config = event.config;

  // tab navigasi anchor
  const tabs = [
    { id: "overview", label: "Overview", icon: Target },
    { id: "divisions", label: "Kelas Pertandingan", icon: Trophy },
    { id: "contingents", label: "Kontingen", icon: Users },
    { id: "bracket", label: "Bracket", icon: Trophy },
    { id: "schedule", label: "Jadwal", icon: Clock },
    { id: "standings", label: "Klasemen", icon: Users },
  ];

  return (
    <div className="min-h-screen">
      {/* === HERO / POSTER === */}
      <div className="relative border-b">
        <div className="container py-12 md:py-16">
          <div className="flex flex-wrap items-center gap-2">
            <Badge variant="secondary">{type.label}</Badge>
            <Badge variant={status.variant}>{status.label}</Badge>
          </div>
          <h1 className="mt-4 max-w-3xl font-serif text-3xl font-semibold leading-tight tracking-tight md:text-5xl">
            {event.name}
          </h1>
          {event.description && (
            <p className="mt-4 max-w-2xl text-muted-foreground md:text-lg">
              {event.description}
            </p>
          )}

          {/* CTA daftar */}
          {(event.status === "REGISTRATION_OPEN" || event.status === "DRAFT") && (
            <div className="mt-6 flex flex-wrap gap-3">
              <Button asChild size="lg">
                <a href={`/events/${event.slug}/register`}>
                  Daftar Sekarang
                </a>
              </Button>
            </div>
          )}

          {/* meta info */}
          <div className="mt-6 grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
            <div className="flex items-center gap-3 rounded-md border bg-card px-4 py-3">
              <Calendar className="h-5 w-5 shrink-0 text-primary" />
              <div className="text-sm">
                <div className="font-medium">Tanggal</div>
                <div className="text-muted-foreground">
                  {formatDateRange(event.startDate, event.endDate)}
                </div>
              </div>
            </div>
            {event.venue && (
              <div className="flex items-center gap-3 rounded-md border bg-card px-4 py-3">
                <MapPin className="h-5 w-5 shrink-0 text-primary" />
                <div className="text-sm">
                  <div className="font-medium">Lokasi</div>
                  <div className="text-muted-foreground">{event.venue}</div>
                </div>
              </div>
            )}
            {config && (
              <div className="flex items-center gap-3 rounded-md border bg-card px-4 py-3">
                <Users className="h-5 w-5 shrink-0 text-primary" />
                <div className="text-sm">
                  <div className="font-medium">Registrasi</div>
                  <div className="text-muted-foreground">
                    {config.registrationType === "HYBRID"
                      ? "Individu + Kontingen"
                      : config.registrationType === "TEAM"
                      ? "Per Kontingen"
                      : "Individu"}
                  </div>
                </div>
              </div>
            )}
          </div>
        </div>
      </div>

      {/* === STATS BAR === */}
      <div className="border-b bg-secondary/30">
        <div className="container grid grid-cols-3 divide-x divide-border">
          <StatBox value={participantCount} label="Peserta" />
          <StatBox value={event.contingents.length} label="Kontingen" />
          <StatBox value={matchCount} label="Pertandingan" />
        </div>
      </div>

      {/* === CONTENT === */}
      <div className="container space-y-16 py-14 md:py-20">
        {/* OVERVIEW */}
        <section id="overview" className="scroll-mt-20">
          <SectionTitle
            icon={Target}
            title="Overview"
            subtitle="Informasi umum kejuaraan"
          />
          <div className="grid gap-6 md:grid-cols-3">
            <InfoCard title="Format Kompetisi">
              {event.divisions.some((d) => d.format === "GROUP_KNOCKOUT") &&
                "Grup → Knockout"}
              {event.divisions.some((d) => d.format === "SCORING") &&
                " • Penilaian Juri"}
            </InfoCard>
            {config?.disciplines && (
              <InfoCard title="Cabang">
                {(config.disciplines as string[]).join(", ")}
              </InfoCard>
            )}
            {config?.ageCategories && (
              <InfoCard title="Kategori Umur">
                {(config.ageCategories as string[]).join(", ")}
              </InfoCard>
            )}
          </div>

          {/* kontak */}
          {(event.contactName || event.contactPhone || event.contactEmail) && (
            <div className="mt-6 rounded-lg border bg-card p-6">
              <h3 className="font-serif text-lg font-semibold">Kontak Panitia</h3>
              <div className="mt-3 grid gap-3 sm:grid-cols-3">
                {event.contactName && (
                  <div className="flex items-center gap-2 text-sm">
                    <Users className="h-4 w-4 text-muted-foreground" />
                    {event.contactName}
                  </div>
                )}
                {event.contactPhone && (
                  <a href={`tel:${event.contactPhone}`} className="flex items-center gap-2 text-sm hover:text-primary">
                    <Phone className="h-4 w-4 text-muted-foreground" />
                    {event.contactPhone}
                  </a>
                )}
                {event.contactEmail && (
                  <a href={`mailto:${event.contactEmail}`} className="flex items-center gap-2 text-sm hover:text-primary">
                    <Mail className="h-4 w-4 text-muted-foreground" />
                    {event.contactEmail}
                  </a>
                )}
              </div>
            </div>
          )}
        </section>

        {/* DIVISIONS */}
        <section id="divisions" className="scroll-mt-20">
          <SectionTitle
            icon={Trophy}
            title="Kelas Pertandingan"
            subtitle="Daftar kelas dan kategori yang dipertandingkan"
          />
          <DivisionList divisions={event.divisions} />
        </section>

        {/* CONTINGENTS */}
        <section id="contingents" className="scroll-mt-20">
          <SectionTitle
            icon={Users}
            title="Kontingen Peserta"
            subtitle={`${event.contingents.length} kontingen terdaftar`}
          />
          {event.contingents.length === 0 ? (
            <div className="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">
              Belum ada kontingen terdaftar.
            </div>
          ) : (
            <div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
              {event.contingents.map((c) => (
                <div
                  key={c.id}
                  className="flex items-center gap-3 rounded-md border bg-card px-4 py-3"
                >
                  <div className="flex h-10 w-10 shrink-0 items-center justify-center rounded-md bg-accent text-accent-foreground font-serif font-semibold">
                    {c.name.charAt(0)}
                  </div>
                  <div className="min-w-0">
                    <div className="truncate font-medium">{c.name}</div>
                    <div className="text-xs text-muted-foreground">
                      {c.type === "CLUB" ? "Perguruan" : c.type === "PROVINCE" ? "Provinsi" : c.type === "COUNTRY" ? "Negara" : "Lainnya"}
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </section>

        {/* BRACKET */}
        <section id="bracket" className="scroll-mt-20">
          <SectionTitle
            icon={Trophy}
            title="Bracket & Hasil Pertandingan"
            subtitle="Pilih kelas untuk melihat bracket dan hasil"
          />
          <BracketExplorer divisions={event.divisions} />
        </section>

        {/* SCHEDULE */}
        <section id="schedule" className="scroll-mt-20">
          <SectionTitle
            icon={Clock}
            title="Jadwal"
            subtitle="Timeline pertandingan per hari"
          />
          <ScheduleTimeline items={event.schedule} />
        </section>

        {/* STANDINGS */}
        <section id="standings" className="scroll-mt-20">
          <SectionTitle
            icon={Users}
            title="Klasemen Kontingen"
            subtitle="Perolehan medali akumulasi — Overall Champion"
          />
          <MedalTable standings={standings} />
        </section>
      </div>
    </div>
  );
}

function StatBox({ value, label }: { value: number; label: string }) {
  return (
    <div className="px-4 py-8 text-center">
      <div className="font-serif text-2xl font-semibold text-primary md:text-3xl">
        {value.toLocaleString("id-ID")}
      </div>
      <div className="mt-1 text-xs uppercase tracking-wider text-muted-foreground">
        {label}
      </div>
    </div>
  );
}

function SectionTitle({
  icon: Icon,
  title,
  subtitle,
}: {
  icon: typeof Target;
  title: string;
  subtitle: string;
}) {
  return (
    <div className="mb-6">
      <div className="flex items-center gap-2">
        <div className="flex h-8 w-8 items-center justify-center rounded-md bg-primary/10 text-primary">
          <Icon className="h-4 w-4" />
        </div>
        <h2 className="font-serif text-2xl font-semibold tracking-tight md:text-3xl">
          {title}
        </h2>
      </div>
      <p className="mt-1.5 pl-10 text-sm text-muted-foreground">{subtitle}</p>
    </div>
  );
}

function InfoCard({ title, children }: { title: string; children: React.ReactNode }) {
  return (
    <div className="rounded-lg border bg-card p-5">
      <div className="text-xs font-medium uppercase tracking-wider text-muted-foreground">
        {title}
      </div>
      <div className="mt-1.5 font-medium">{children || "—"}</div>
    </div>
  );
}

// frontend/app/pages/events/[slug].vue
<script setup lang="ts">
const route = useRoute();
const config = useRuntimeConfig();
const slug = computed(() => route.params.slug as string);

const { data: resp, error } = await useFetch<any>(`${config.public.apiBase}/events/${slug.value}`);
if (error.value || !resp.value?.event) {
  throw createError({ statusCode: 404, statusMessage: 'Event tidak ditemukan', fatal: true });
}

const event = computed(() => resp.value.event);
const stats = computed(() => resp.value.stats);
const standings = computed<any[]>(() => resp.value.standings || []);

const statusLabel: Record<string, string> = {
  DRAFT: 'Draft', REGISTRATION_OPEN: 'Pendaftaran Dibuka', UPCOMING: 'Segera Hadir',
  ONGOING: 'Sedang Berlangsung', COMPLETED: 'Selesai', CANCELLED: 'Dibatalkan',
};
const statusVariant: Record<string, string> = {
  REGISTRATION_OPEN: 'bg-amber-100 text-amber-800',
  UPCOMING: 'bg-primary text-primary-foreground',
  ONGOING: 'bg-emerald-100 text-emerald-800',
};
const typeLabel: Record<string, string> = {
  CHAMPIONSHIP: 'Kejuaraan', LEAGUE: 'Liga', FESTIVAL: 'Festival', MICE: 'Konferensi', OTHER: 'Event',
};
const genderLabel: Record<string, string> = { PUTRA: 'Putra', PUTRI: 'Putri', MIXED: 'Campuran' };
const formatLabel: Record<string, string> = {
  FULL_KNOCKOUT: 'Knockout',
  GROUP_KNOCKOUT: 'Grup → Knockout',
  ROUND_ROBIN: 'Liga',
  SCORING: 'Penilaian',
  NON_COMPETITIVE: 'Non-kompetitif',
};
const contingentType: Record<string, string> = { CLUB: 'Perguruan', PROVINCE: 'Provinsi', COUNTRY: 'Negara', OTHER: 'Lainnya' };

function fmtRange(start: string, end: string) {
  const s = new Date(start), e = new Date(end);
  const fmt = (d: Date) => d.toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' });
  return s.toDateString() === e.toDateString() ? fmt(s) : `${fmt(s)} — ${fmt(e)}`;
}
function fmtDate(d: string) {
  return new Date(d).toLocaleDateString('id-ID', { day: 'numeric', month: 'long', year: 'numeric' });
}
function fmtTime(d: string) {
  return new Date(d).toLocaleTimeString('id-ID', { hour: '2-digit', minute: '2-digit' });
}

// Kelompokkan divisions per disiplin
const groupedDivisions = computed(() => {
  const map: Record<string, any[]> = {};
  for (const d of event.value.divisions || []) {
    (map[d.discipline] = map[d.discipline] || []).push(d);
  }
  return map;
});

// Kelompokkan schedule per hari
const groupedSchedule = computed(() => {
  const map: Record<string, any[]> = {};
  for (const s of event.value.schedule || []) {
    const day = fmtDate(s.time);
    (map[day] = map[day] || []).push(s);
  }
  return map;
});

useHead({ title: `${event.value.name} — EO Sanasini` });
</script>

<template>
  <div class="min-h-screen">
    <!-- HERO -->
    <div class="border-b bg-secondary/30">
      <div class="container-x py-12 md:py-16">
        <div class="flex flex-wrap items-center gap-2">
          <span class="rounded-full border bg-card px-2.5 py-0.5 text-xs font-medium">{{ typeLabel[event.type] || event.type }}</span>
          <span :class="['rounded-full px-2.5 py-0.5 text-xs font-medium', statusVariant[event.status] || 'border border-border']">
            {{ statusLabel[event.status] || event.status }}
          </span>
        </div>
        <h1 class="mt-4 max-w-3xl text-3xl font-semibold leading-tight tracking-tight md:text-5xl">{{ event.name }}</h1>
        <p v-if="event.description" class="mt-4 max-w-2xl text-muted-foreground md:text-lg">{{ event.description }}</p>

        <!-- CTA -->
        <div v-if="event.status === 'REGISTRATION_OPEN'" class="mt-6">
          <a :href="`/events/${event.slug}/register`" class="inline-flex h-12 items-center justify-center rounded-md bg-primary px-8 text-base font-medium text-primary-foreground hover:bg-primary/90">
            Daftar Sekarang
          </a>
        </div>

        <!-- Meta -->
        <div class="mt-6 grid gap-3 sm:grid-cols-3">
          <div class="flex items-center gap-3 rounded-md border bg-card px-4 py-3 text-sm">
            <span class="text-primary">📅</span>
            <div>
              <div class="font-medium">Tanggal</div>
              <div class="text-muted-foreground">{{ fmtRange(event.start_date, event.end_date) }}</div>
            </div>
          </div>
          <div v-if="event.venue" class="flex items-center gap-3 rounded-md border bg-card px-4 py-3 text-sm">
            <span class="text-primary">📍</span>
            <div>
              <div class="font-medium">Lokasi</div>
              <div class="text-muted-foreground">{{ event.venue }}</div>
            </div>
          </div>
          <div v-if="event.config" class="flex items-center gap-3 rounded-md border bg-card px-4 py-3 text-sm">
            <span class="text-primary">👥</span>
            <div>
              <div class="font-medium">Registrasi</div>
              <div class="text-muted-foreground">
                {{ event.config.registration_type === 'HYBRID' ? 'Individu + Kontingen' : event.config.registration_type === 'TEAM' ? 'Per Kontingen' : 'Individu' }}
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>

    <!-- STATS -->
    <div class="border-b">
      <div class="container-x grid grid-cols-3 divide-x divide-border">
        <div class="px-4 py-8 text-center">
          <div class="text-2xl font-semibold text-primary md:text-3xl">{{ stats.participants }}</div>
          <div class="mt-1 text-xs uppercase tracking-wider text-muted-foreground">Peserta</div>
        </div>
        <div class="px-4 py-8 text-center">
          <div class="text-2xl font-semibold text-primary md:text-3xl">{{ stats.contingents }}</div>
          <div class="mt-1 text-xs uppercase tracking-wider text-muted-foreground">Kontingen</div>
        </div>
        <div class="px-4 py-8 text-center">
          <div class="text-2xl font-semibold text-primary md:text-3xl">{{ stats.matches }}</div>
          <div class="mt-1 text-xs uppercase tracking-wider text-muted-foreground">Pertandingan</div>
        </div>
      </div>
    </div>

    <!-- CONTENT -->
    <div class="container-x space-y-16 py-14 md:py-20">
      <!-- DIVISIONS (sport only) -->
      <section v-if="event.category === 'SPORT' && (event.divisions?.length || 0) > 0" id="divisions">
        <div class="mb-6">
          <h2 class="text-2xl font-semibold tracking-tight md:text-3xl">Kelas Pertandingan</h2>
          <p class="mt-1.5 text-sm text-muted-foreground">Daftar kelas dan kategori yang dipertandingkan</p>
        </div>
        <div class="space-y-8">
          <div v-for="(divs, discipline) in groupedDivisions" :key="discipline">
            <h3 class="mb-3 text-lg font-semibold">{{ discipline }}</h3>
            <div class="grid gap-2 sm:grid-cols-2">
              <div v-for="d in divs" :key="d.id" class="flex items-center justify-between rounded-md border bg-card px-4 py-3">
                <div>
                  <div class="font-medium">{{ d.age_category }} — {{ genderLabel[d.gender] }}</div>
                  <div class="text-sm text-muted-foreground">{{ d.class_name }}</div>
                </div>
                <span class="shrink-0 rounded-full border px-2 py-0.5 text-xs">{{ formatLabel[d.format] || d.format }}</span>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- CONTINGENTS -->
      <section v-if="event.contingents?.length" id="contingents">
        <div class="mb-6">
          <h2 class="text-2xl font-semibold tracking-tight md:text-3xl">Kontingen Peserta</h2>
          <p class="mt-1.5 text-sm text-muted-foreground">{{ event.contingents.length }} kontingen terdaftar</p>
        </div>
        <div class="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">
          <div v-for="c in event.contingents" :key="c.id" class="flex items-center gap-3 rounded-md border bg-card px-4 py-3">
            <div class="flex h-10 w-10 shrink-0 items-center justify-center rounded-md bg-accent font-serif font-semibold">
              {{ c.name.charAt(0) }}
            </div>
            <div class="min-w-0">
              <div class="truncate font-medium">{{ c.name }}</div>
              <div class="text-xs text-muted-foreground">{{ contingentType[c.type] || c.type }}</div>
            </div>
          </div>
        </div>
      </section>

      <!-- SCHEDULE -->
      <section v-if="event.schedule?.length" id="schedule">
        <div class="mb-6">
          <h2 class="text-2xl font-semibold tracking-tight md:text-3xl">Jadwal</h2>
          <p class="mt-1.5 text-sm text-muted-foreground">Timeline pertandingan per hari</p>
        </div>
        <div class="space-y-8">
          <div v-for="(items, day) in groupedSchedule" :key="day">
            <h3 class="mb-4 text-lg font-semibold text-primary">{{ day }}</h3>
            <div class="relative space-y-4 border-l-2 border-border pl-6">
              <div v-for="item in items" :key="item.id" class="relative">
                <span class="absolute -left-[27px] top-1.5 h-3 w-3 rounded-full border-2 border-background bg-primary" />
                <div class="flex flex-col sm:flex-row sm:items-baseline sm:gap-3">
                  <span class="shrink-0 font-mono text-sm font-medium text-primary">{{ fmtTime(item.time) }}</span>
                  <div>
                    <div class="font-medium">{{ item.title }}</div>
                    <div v-if="item.notes" class="text-sm text-muted-foreground">{{ item.notes }}</div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <!-- BRACKET (sport only) -->
      <section v-if="event.category === 'SPORT' && (event.divisions?.length || 0) > 0" id="bracket">
        <div class="mb-6">
          <h2 class="text-2xl font-semibold tracking-tight md:text-3xl">Bracket &amp; Hasil Pertandingan</h2>
          <p class="mt-1.5 text-sm text-muted-foreground">Pilih kelas untuk melihat bracket</p>
        </div>
        <EventsBracketExplorer :divisions="event.divisions" />
      </section>

      <!-- STANDINGS -->
      <section v-if="event.category === 'SPORT'" id="standings">
        <div class="mb-6">
          <h2 class="text-2xl font-semibold tracking-tight md:text-3xl">Klasemen Kontingen</h2>
          <p class="mt-1.5 text-sm text-muted-foreground">Perolehan medali akumulasi — Overall Champion</p>
        </div>
        <div v-if="standings.length === 0" class="rounded-lg border border-dashed p-8 text-center text-sm text-muted-foreground">
          Belum ada medali yang dibagikan.
        </div>
        <div v-else class="overflow-x-auto rounded-lg border">
          <table class="w-full min-w-[480px] text-sm">
            <thead class="bg-secondary/50">
              <tr class="text-left">
                <th class="px-4 py-3 font-semibold">#</th>
                <th class="px-4 py-3 font-semibold">Kontingen</th>
                <th class="px-3 py-3 text-center font-semibold">🥇</th>
                <th class="px-3 py-3 text-center font-semibold">🥈</th>
                <th class="px-3 py-3 text-center font-semibold">🥉</th>
                <th class="px-4 py-3 text-center font-semibold">Total</th>
              </tr>
            </thead>
            <tbody class="divide-y">
              <tr v-for="s in standings" :key="s.contingent?.id || s.rank" :class="s.rank === 1 ? 'bg-accent/40' : ''">
                <td class="px-4 py-3 font-medium">{{ s.rank === 1 ? '🏆' : '' }} {{ s.rank }}</td>
                <td class="px-4 py-3 font-medium">{{ s.contingent?.name }}</td>
                <td class="px-3 py-3 text-center font-semibold text-primary">{{ s.gold }}</td>
                <td class="px-3 py-3 text-center text-muted-foreground">{{ s.silver }}</td>
                <td class="px-3 py-3 text-center text-muted-foreground">{{ s.bronze }}</td>
                <td class="px-4 py-3 text-center font-bold">{{ s.total }}</td>
              </tr>
            </tbody>
          </table>
        </div>
      </section>
    </div>
  </div>
</template>
